name: Request-whoogle-search-instance

on:
  schedule:
    # Runs "At minute 20 past every hour from 7 through 23." (see https://crontab.guru)
    - cron: '*/20 7-23 * * *'
jobs:
  build:
    name: Request whoogle-search instance
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl https://whooglego.herokuapp.com/
